<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd" >
<#assign modelName = table2ModelStrategy.getModelName(table.getName()) >
<mapper namespace="${myBatisMapperPackage}.${modelName}Mapper">
	
	<!-- timestamp: ${time} -->
	
	<#-- 寻找主键 -->
	<#assign primaryKeyColumnName = "">
	<#assign primaryKeyPropertyName = "">
	<#assign primaryKeyJDBCType = "">
	<#list table.columnList as column >
		<#if column.isPrimaryKey>
			<#assign primaryKeyColumnName = column.name>
			<#assign primaryKeyPropertyName = column2PropStrategy.getPropName(column.name)>
			<#assign primaryKeyJDBCType = SQL_TPYE_MYBATIS_JDBC_TYPE_MAP[column.type]>
		</#if>
	</#list>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<resultMap id="BaseResultMap" type="${package}.${modelName}">
		<#list table.columnList as column >
		<#if column.isPrimaryKey>
		<id column="${column.name}" property="${column2PropStrategy.getPropName(column.name)}" jdbcType="${SQL_TPYE_MYBATIS_JDBC_TYPE_MAP[column.type]}" />
		<#else>
		<result column="${column.name}" property="${column2PropStrategy.getPropName(column.name)}" jdbcType="${SQL_TPYE_MYBATIS_JDBC_TYPE_MAP[column.type]}" />
		</#if>
		</#list>
	</resultMap>

	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<sql id="Base_Column_List">
		<#list table.columnList as column >${column.name}<#if column_has_next >, </#if><#if column_index != 0 && column_index % 8 == 0 >${"\r\n\t\t"}</#if></#list>
	</sql>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<sql id="Example_Where_Clause">
		<where>
			<foreach collection="example.orCriteria" item="criteria" separator="or">
				<if test="criteria.notEmpty">
					<trim prefix="(" prefixOverrides="and" suffix=")" >
						<foreach collection="criteria.criteria" item="criterion">
							<choose>
								<when test="criterion.isNoValue">
									and $${r"{criterion.condition}"}}
								</when>
								<when test="criterion.isSingleValue">
									and $${r"{criterion.condition}"}} #${r"{"}criterion.value${r"}"}
								</when>
								<when test="criterion.isBetweenValue">
									and $${r"{criterion.condition}"}} #${r"{"}criterion.value${r"}"} and #${r"{"}criterion.secondValue${r"}"}
								</when>
								<when test="criterion.isListValue">
									and $${r"{criterion.condition}"}}
										<foreach collection="criterion.value" item="item" open="(" close=")" separator=",">
											#${r"{"}item${r"}"}
										</foreach>
								</when>
							</choose>
						</foreach>
					</trim>
				</if>
			</foreach>
		</where>
	</sql>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<insert id="insert" parameterType="${package}.${modelName}">
		insert into ${table.getName()} ( <include refid="Base_Column_List" /> )
		values (
			<#list table.columnList as column>#${r"{"}${column2PropStrategy.getPropName(column.name)}${r"}"}<#if column_has_next >, </#if><#if column_index != 0 && column_index % 8 == 0 >${"\r\n\t\t\t"}</#if></#list>
		)
	</insert>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<insert id="insertSelective" parameterType="${package}.${modelName}">
		insert into ${table.getName()}
		<trim prefix="(" suffix=")" suffixOverrides=",">
			<#list table.columnList as column>
			<if test="${column2PropStrategy.getPropName(column.name)} != null">${column.name},</if>
			</#list>
		</trim>
		<trim prefix="values (" suffix=")" suffixOverrides=",">
			<#list table.columnList as column>
			<if test="${column2PropStrategy.getPropName(column.name)} != null">#${r"{"}${column2PropStrategy.getPropName(column.name)}${r"}"},</if>
			</#list>
		</trim>
	</insert>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<delete id="deleteByPrimaryKey" parameterType="java.lang.String">
		delete from ${table.getName()}
		where ${primaryKeyColumnName} = #${r"{"}${primaryKeyPropertyName}${r"}"}
	</delete>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<delete id="deleteByExample">
		<if test="example != null">
			delete from ${table.getName()}
			<include refid="Example_Where_Clause"/>
		</if>
	</delete>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<update id="updateByPrimaryKey" parameterType="${package}.${modelName}">
		update ${table.getName()}
		set
			<#list table.columnList as column><#if !column.isPrimaryKey>${column.name} = #${r"{"}${column2PropStrategy.getPropName(column.name)}${r"}"}<#if column_has_next >, </#if></#if><#if column_index != 0 && column_index % 3 == 0 >${"\r\n\t\t\t"}</#if></#list>
		where ${primaryKeyColumnName} = #${r"{"}${primaryKeyPropertyName}${r"}"}
	</update>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<update id="updateByPrimaryKeySelective" parameterType="${package}.${modelName}">
		update ${table.getName()}
		<set>
			<#list table.columnList as column>
				<#if !column.isPrimaryKey><if test="${column2PropStrategy.getPropName(column.name)} != null">${column.name} = #${r"{"}${column2PropStrategy.getPropName(column.name)}${r"}"},</if></#if>
			</#list>
		</set>
		where ${primaryKeyColumnName} = #${r"{"}${primaryKeyPropertyName}${r"}"}
	</update>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<update id="updateByExampleSelective">
		<if test="example != null">
			update ${table.getName()}
			<set>
				<#list table.columnList as column>
					<#if !column.isPrimaryKey><if test="${column2PropStrategy.getPropName(column.name)} != null">${column.name} = #${r"{"}${column2PropStrategy.getPropName(column.name)}${r"}"},</if></#if>
				</#list>
			</set>
			<include refid="Example_Where_Clause" />
		</if>
	</update>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<select id="getById" resultMap="BaseResultMap" parameterType="java.lang.String">
		select
		<include refid="Base_Column_List" />
		from ${table.getName()}
		where ${primaryKeyColumnName} = #${r"{"}${primaryKeyPropertyName}${r"}"}
	</select>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<select id="getObjectByExample" resultMap="BaseResultMap">
		select <include refid="Base_Column_List" />
		from ${table.getName()}
		<if test="example != null">
			<include refid="Example_Where_Clause"/>
		</if>
	</select>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<select id="getListByExample" resultMap="BaseResultMap">
		select <if test="example != null and example.distinct">distinct</if> <include refid="Base_Column_List" />
		from ${table.getName()}
		<if test="example != null">
			<include refid="Example_Where_Clause"/>
		</if>
		<if test="example != null and example.orderByClause != null and example.orderByClause != ''">
			order by $${r"{example.orderByClause}"}
		</if>
	</select>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<select id="getCountByExample" resultType="java.lang.Long" >
		select count(1) from ${table.getName()}
		<if test="example != null">
			<include refid="Example_Where_Clause"/>
		</if>
	</select>
	
</mapper>