<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd" >
<#assign modelName = table2ModelStrategy.getModelName(table.getName()) >
<mapper namespace="${myBatisMapperPackage}.${modelName}Mapper">
	
	<!-- timestamp: ${time} -->
	
	<#-- 寻找主键 -->
	<#assign primaryKeyColumnName = "">
	<#assign primaryKeyPropertyName = "">
	<#assign primaryKeyJDBCType = "">
	<#list table.columnList as column >
		<#if column.isPrimaryKey>
			<#assign primaryKeyColumnName = column.name>
			<#assign primaryKeyPropertyName = column2PropStrategy.getPropName(column.name)>
			<#assign primaryKeyJDBCType = SQL_TPYE_MYBATIS_JDBC_TYPE_MAP[column.type]>
		</#if>
	</#list>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<resultMap id="BaseResultMap" type="${package}.${modelName}">
		<#list table.columnList as column >
		<#if column.isPrimaryKey>
		<id column="${column.name}" property="${column2PropStrategy.getPropName(column.name)}" jdbcType="${SQL_TPYE_MYBATIS_JDBC_TYPE_MAP[column.type]}" />
		<#else>
		<result column="${column.name}" property="${column2PropStrategy.getPropName(column.name)}" jdbcType="${SQL_TPYE_MYBATIS_JDBC_TYPE_MAP[column.type]}" />
		</#if>
		</#list>
	</resultMap>

	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<sql id="Base_Column_List">
		<#list table.columnList as column >
		${column.name}<#if column_has_next >,</#if>
		</#list>
	</sql>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<insert id="insert" parameterType="${package}.${modelName}">
		insert into ${table.getName()} (
			<include refid="Base_Column_List" />
		)
		values (
			<#list table.columnList as column>
				#${r"{"}${column2PropStrategy.getPropName(column.name)}${r"}"}<#if column_has_next >,</#if>
			</#list>
		)
	</insert>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<insert id="insertSelective" parameterType="${package}.${modelName}">
		insert into ${table.getName()}
		<trim prefix="(" suffix=")" suffixOverrides=",">
			<#list table.columnList as column>
			<if test="${column2PropStrategy.getPropName(column.name)} != null">
				${column.name},
			</if>
			</#list>
		</trim>
		<trim prefix="values (" suffix=")" suffixOverrides=",">
			<#list table.columnList as column>
			<if test="${column2PropStrategy.getPropName(column.name)} != null">
				#${r"{"}${column2PropStrategy.getPropName(column.name)}${r"}"},
			</if>
			</#list>
		</trim>
	</insert>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<delete id="deleteByPrimaryKey" parameterType="java.lang.String">
		delete from ${table.getName()}
		where ${primaryKeyColumnName} = #${r"{"}${primaryKeyPropertyName}${r"}"}
	</delete>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<update id="updateByPrimaryKey" parameterType="${package}.${modelName}">
		update ${table.getName()}
		set
			<#list table.columnList as column>
			<#if !column.isPrimaryKey>
			${column.name} = #${r"{"}${column2PropStrategy.getPropName(column.name)}${r"}"}<#if column_has_next >,</#if>
			</#if>
			</#list>
		where ${primaryKeyColumnName} = #${r"{"}${primaryKeyPropertyName}${r"}"}
	</update>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<update id="updateByPrimaryKeySelective" parameterType="${package}.${modelName}">
		update ${table.getName()}
		<set>
			<#list table.columnList as column>
			<#if !column.isPrimaryKey>
			<if test="${column2PropStrategy.getPropName(column.name)} != null">
				${column.name} = #${r"{"}${column2PropStrategy.getPropName(column.name)}${r"}"},
			</if>
			</#if>
			</#list>
		</set>
		where ${primaryKeyColumnName} = #${r"{"}${primaryKeyPropertyName}${r"}"}
	</update>
	
	<!-- WARNING - This element is automatically generated by CodeGen, do not modify. -->
	<select id="selectByPrimaryKey" resultMap="BaseResultMap" parameterType="java.lang.String">
		select
		<include refid="Base_Column_List" />
		from ${table.getName()}
		where ${primaryKeyColumnName} = #${r"{"}${primaryKeyPropertyName}${r"}"}
	</select>
	
</mapper>